<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Assigned users</strong> are allowed to process this task.' => 'يُسمح للمستخدمين المعينين بأداء هذه المهمة',
    '<strong>Create</strong> task list' => 'إنشاء قائمة مهام',
    '<strong>Edit</strong> task list' => 'تحرير قائمة المهام',
    '<strong>Task</strong> Overview' => 'نظرة عامة على المهام',
    'Accept Task' => 'قبول المهمة',
    'Add Task List' => 'إضافة قائمة مهام',
    'Add task' => 'إضافة مهمة',
    'Allows the user to create new tasks, the user will only be able to edit and delete own tasks' => 'يسمح للمستخدم بإنشاء مهام جديدة ، لن يتمكن المستخدم إلا من تحرير وحذف مهامه الخاصة',
    'Assignments:' => 'المهام',
    'Balance' => 'الرصيد',
    'Begin Task' => 'بدء المهمة',
    'Checklist:' => 'قائمة التحقق',
    'Close' => 'اغلاق',
    'Continue Review' => 'متابعة المراجعة',
    'Create tasks' => 'إنشاء المهام',
    'Delete' => 'حذف',
    'Delete list' => 'حذف القائمة',
    'Delete task' => 'حذف المهمة',
    'Edit' => 'تحرير',
    'Edit list' => 'تحرير القائمة',
    'Edit task' => 'تحرير المهمة',
    'Finish Task' => 'إنهاء المهمة',
    'Finished Lists' => 'القوائم المنتهية',
    'Here you can manage your task lists in order to categorize and sort tasks.' => 'هنا يمكنك إدارة قوائم المهام الخاصة بك من أجل تصنيف المهام وفرزها',
    'Hide this list once all tasks are completed' => 'إخفاء هذه القائمة بمجرد اكتمال جميع المهام',
    'If no assigned user is selected, every space member with the permission to process unassigned tasks can process the task.' => 'إذا لم يتم تعيين أي مستخدم ، يمكن لكل عضو في الفضاء لديه الإذن للعمل في المهام غير المعينة القيام بالمهمة',
    'In case the review option is active, a <strong>responsible user</strong> will have to review and either reject or confirm this task before completion.' => 'في حالة تنشيط خيار المراجعة ، يجب على المستخدم المسؤول مراجعة هذه المهمة وإما رفضها أو تأكيدها قبل الإكمال',
    'Invalid task list selection.' => 'اختيار قائمة المهام غير صالح',
    'Let Task Review' => 'السماح بمراجعة المهمة',
    'List' => 'قائمة',
    'Lists' => 'القوائم',
    'No pending tasks found' => 'لم يتم العثور على مهام مفتوحة',
    'No results found for the given filter.' => 'لا توجد نتائج لعامل التصفية المحدد',
    'Other Tasks' => 'مهام أخرى',
    'Ready For Review' => 'جاهز للمراجعة',
    'Reject Task' => 'رفض المهمة',
    'Request extension' => 'طلب التمديد',
    'Reset Task' => 'إعادة تعيين المهمة',
    'Scheduling' => 'جدولة',
    'Search' => 'بحث',
    'Show {count} more completed {n,plural,=1{task} other{tasks}}' => 'إظهار المزيد من المهام المكتملة',
    'Task' => 'المهمة',
    'Task Lists' => 'قوائم المهام',
    'Tasks' => 'المهام',
    'Tasks: Reminder' => 'المهام: تذكير',
    'This task requires to be reviewed by a responsible' => 'هذه المهمة تتطلب مراجعتها من قبل مسؤول',
    'Toggle lists' => 'تبديل القوائم',
    'Unsorted' => 'غير مصنف',
    'Updated' => 'محدث',
    'You are assigned!' => 'تم تعيينك',
    'You are responsible!' => 'أنت مسؤول',
    'view all' => 'عرض الكل',
    '{displayName} is assigned to this task' => 'لهذه المهمة {displayName} تم تعيين',
    '{displayName} is responsible for this task' => ' مسؤول عن هذه المهمة {displayName}',
    'Public' => 'عام',
];
