<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Assigned users</strong> are allowed to process this task.' => '@@@@',
    '<strong>Create</strong> task list' => '@@@@',
    '<strong>Edit</strong> task list' => '@@@@',
    '<strong>Task</strong> Overview' => '@@@@',
    'Accept Task' => '@@@@',
    'Add Task List' => '@@@@',
    'Add task' => '@@@@',
    'Allows the user to create new tasks, the user will only be able to edit and delete own tasks' => '@@@@',
    'Assignments:' => '@@@@',
    'Balance' => '@@@@',
    'Begin Task' => '@@@@',
    'Checklist:' => '@@@@',
    'Close' => '@@@@',
    'Continue Review' => '@@@@',
    'Create tasks' => '@@@@',
    'Delete' => '@@@@',
    'Delete list' => '@@@@',
    'Delete task' => '@@@@',
    'Edit' => '@@@@',
    'Edit list' => '@@@@',
    'Edit task' => '@@@@',
    'Finish Task' => '@@@@',
    'Finished Lists' => '@@@@',
    'Here you can manage your task lists in order to categorize and sort tasks.' => '@@@@',
    'Hide this list once all tasks are completed' => '@@@@',
    'If no assigned user is selected, every space member with the permission to process unassigned tasks can process the task.' => '@@@@',
    'In case the review option is active, a <strong>responsible user</strong> will have to review and either reject or confirm this task before completion.' => '@@@@',
    'Invalid task list selection.' => '@@@@',
    'Let Task Review' => '@@@@',
    'List' => '@@@@',
    'Lists' => '@@@@',
    'No pending tasks found' => '@@@@',
    'No results found for the given filter.' => '@@@@',
    'Other Tasks' => '@@@@',
    'Ready For Review' => '@@@@',
    'Reject Task' => '@@@@',
    'Request extension' => '@@@@',
    'Reset Task' => '@@@@',
    'Scheduling' => '@@@@',
    'Search' => '@@@@',
    'Show {count} more completed {n,plural,=1{task} other{tasks}}' => '@@@@',
    'Task' => '@@@@',
    'Task Lists' => '@@@@',
    'Tasks' => '@@@@',
    'Tasks: Reminder' => '@@@@',
    'This task requires to be reviewed by a responsible' => '@@@@',
    'Toggle lists' => '@@@@',
    'Unsorted' => '@@@@',
    'Updated' => '@@@@',
    'You are assigned!' => '@@@@',
    'You are responsible!' => '@@@@',
    'view all' => '@@@@',
    '{displayName} is assigned to this task' => '@@@@',
    '{displayName} is responsible for this task' => '@@@@',
    'Public' => '@@@@',
];
